version: '3.8'

services:
  pythonwithdocker:
    image: pythonwithdocker
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./:/app
    tty: true
